name: Update Confluence Release Notes

on:
  release:
    types: [published]

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to access previous tag and commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atlassian-python-api requests

      - name: Collect commits + PRs and update Confluence
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
        run: |
          import os, subprocess, datetime, requests
          from atlassian import Confluence

          repo_name = os.getenv("GITHUB_REPOSITORY")
          current_tag = os.getenv("GITHUB_REF_NAME")
          github_token = os.getenv("GITHUB_TOKEN")

          # --- find last tag ---
          last_tag = subprocess.getoutput("git tag --sort=-creatordate | sed -n '2p'")
          latest_commit = subprocess.getoutput("git rev-parse HEAD")[:7]

          print(f"🔖 Current Tag: {current_tag}")
          print(f"⬅️ Previous Tag: {last_tag}")

          # --- collect commits ---
          commits_output = subprocess.getoutput(f"git log {last_tag}..{current_tag} --pretty=format:'%s'")
          commit_lines = [line.strip() for line in commits_output.splitlines() if line.strip()]

          # --- collect merged PR titles via GitHub API ---
          headers = {"Authorization": f"Bearer {github_token}"}
          prs = []
          url = f"https://api.github.com/repos/{repo_name}/pulls?state=closed&per_page=100"
          response = requests.get(url, headers=headers)
          if response.ok:
              for pr in response.json():
                  merged_at = pr.get("merged_at")
                  if merged_at:
                      prs.append(pr["title"])

          # Combine and deduplicate
          combined = sorted(set(commit_lines + prs))

          # --- Prepare header ---
          release_date = datetime.datetime.utcnow().strftime("%m-%d-%Y %H:%M")
          header = f"**{repo_name} - {current_tag} - {release_date} - {latest_commit}**"

          print(f"🧾 Preparing section for Confluence: {header}")

          # --- Confluence setup ---
          confluence = Confluence(
              url=os.environ["CONFLUENCE_URL"],
              username=os.environ["CONFLUENCE_USERNAME"],
              password=os.environ["CONFLUENCE_API_TOKEN"],
              cloud=True,
          )

          page_id = os.environ["CONFLUENCE_PAGE_ID"]
          page = confluence.get_page_by_id(page_id=page_id, expand="body.storage")
          page_title = page["title"]
          page_content = page["body"]["storage"]["value"]

          # --- Create HTML block for new release ---
          release_html = (
              f"<p>{header}</p><ul>" +
              "".join(f"<li>{msg}</li>" for msg in combined) +
              "</ul><hr/>"
          )

          # --- Combine and update ---
          new_content = release_html + page_content
          confluence.update_page(
              page_id=page_id,
              title=page_title,
              body=new_content,
              representation="storage",
          )

          print(f"✅ Confluence page updated for release {current_tag}")
