name: Update Confluence Release Notes

on:
  release:
    types: [published]
  # Optional: uncomment below if you also want to trigger on any tag push
  # push:
  #   tags:
  #     - '*'

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensures we can compare previous tag

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atlassian-python-api requests

      - name: Collect commits + PRs and update Confluence
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_API_URL: ${{ github.api_url }}
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
        run: |
          python - <<'EOF'
          import os, subprocess, datetime, requests
          from atlassian import Confluence

          # --- GitHub Environment Info ---
          repo_name = os.getenv("GITHUB_REPOSITORY")
          current_tag = os.getenv("GITHUB_REF_NAME")
          github_token = os.getenv("GITHUB_TOKEN")
          api_base = os.getenv("GITHUB_API_URL", "https://api.github.com")

          # --- Find previous tag ---
          last_tag = subprocess.getoutput("git tag --sort=-creatordate | sed -n '2p'")
          latest_commit = subprocess.getoutput("git rev-parse HEAD")[:7]

          print(f"ðŸ”– Current Tag: {current_tag}")
          print(f"â¬…ï¸ Previous Tag: {last_tag}")
          print(f"ðŸ§± Last Commit: {latest_commit}")

          # --- Collect commits between tags ---
          commits_output = subprocess.getoutput(f"git log {last_tag}..{current_tag} --pretty=format:'%s'")
          commit_lines = [line.strip() for line in commits_output.splitlines() if line.strip()]

          # --- Collect merged PRs ---
          prs = []
          try:
              url = f"{api_base}/repos/{repo_name}/pulls?state=closed&per_page=100"
              headers = {"Authorization": f"Bearer {github_token}"}
              response = requests.get(url, headers=headers, timeout=30)
              if response.ok:
                  for pr in response.json():
                      if pr.get("merged_at"):
                          prs.append(pr["title"])
              else:
                  print(f"âš ï¸ Failed to fetch PRs: {response.status_code} - {response.text}")
          except Exception as e:
              print(f"âš ï¸ Error fetching PRs: {e}")

          # --- Combine and deduplicate ---
          combined = sorted(set(commit_lines + prs))

          # --- Build header ---
          release_date = datetime.datetime.utcnow().strftime("%m-%d-%Y %H:%M")
          header = f"**{repo_name} - {current_tag} - {release_date} - {latest_commit}**"
          print(f"ðŸ§¾ Preparing Confluence update block for: {header}")

          # --- Initialize Confluence client ---
          confluence = Confluence(
              url=os.environ["CONFLUENCE_URL"],
              username=os.environ["CONFLUENCE_USERNAME"],
              password=os.environ["CONFLUENCE_API_TOKEN"],
              cloud=True,
          )

          page_id = os.environ["CONFLUENCE_PAGE_ID"]

          # --- Fetch existing Confluence page ---
          page = confluence.get_page_by_id(page_id=page_id, expand="body.storage")
          page_title = page["title"]
          page_content = page["body"]["storage"]["value"]

          # --- Create release HTML block ---
          release_html = (
              f"<p>{header}</p><ul>" +
              "".join(f"<li>{msg}</li>" for msg in combined) +
              "</ul><hr/>"
          )

          # --- Combine and update ---
          new_content = release_html + page_content
          confluence.update_page(
              page_id=page_id,
              title=page_title,
              body=new_content,
              representation="storage",
          )

          print(f"âœ… Confluence page updated successfully for release {current_tag}")
          EOF
