name: Validate PR Title or Commit Message

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr:
    name: 🧩 Validate PR Title or Commit Message
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 4  # Fetch a few commits for safety

      - name: Validate PR title or commit message
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          set -e

          echo "🔎 PR Title: $PR_TITLE"

          check_patterns() {
            local msg="$1"

            echo "$msg" | grep -qE '^\[HIF-[0-9]+\] .+' && return 0
            echo "$msg" | grep -qE '^\[PLM-P[0-9]+-[0-9]+\] .+' && return 0
            echo "$msg" | grep -qE '^Coding style for "\[HIF-[0-9]+\] .+"' && return 0
            echo "$msg" | grep -qE '^Coding style for "\[PLM-P[0-9]+-[0-9]+\] .+"' && return 0

            return 1
          }

          # ✅ Check PR title first
          if check_patterns "$PR_TITLE"; then
            echo "✅ Valid pattern found in PR title."
            exit 0
          fi

          echo "🔎 Checking commit messages..."

          # Get the last two commit SHAs
          COMMIT_SHAS=($(git log -2 --pretty=format:%H))
          FIRST_COMMIT_MSG=$(git log -1 --pretty=%B "${COMMIT_SHAS[0]}" | tr -d '\r')
          SECOND_COMMIT_MSG=$(git log -1 --pretty=%B "${COMMIT_SHAS[1]}" | tr -d '\r')

          echo "🔸 Latest commit message:"
          echo "$FIRST_COMMIT_MSG"
          echo "🔸 Previous commit message:"
          echo "$SECOND_COMMIT_MSG"

          # Pattern for "Merge <sha> into <sha>"
          MERGE_SHA_PATTERN='^Merge [0-9a-f]{7,40} into [0-9a-f]{7,40}'

          # If latest commit is a merge commit with SHA pattern → skip it
          if echo "$FIRST_COMMIT_MSG" | grep -qE "$MERGE_SHA_PATTERN"; then
            echo "ℹ️ Latest commit is a merge commit (SHA pattern). Checking previous commit..."
            if [ -n "$SECOND_COMMIT_MSG" ] && check_patterns "$SECOND_COMMIT_MSG"; then
              echo "✅ Valid pattern found in previous (non-merge) commit message."
              exit 0
            else
              echo "❌ Previous commit message did not match expected pattern."
              exit 1
            fi
          else
            if check_patterns "$FIRST_COMMIT_MSG"; then
              echo "✅ Valid pattern found in last commit message."
              exit 0
            fi
          fi

          echo "❌ Invalid PR title or commit message."
          echo ""
          echo "PR title or a non-merge commit message must match one of these formats:"
          echo "  [HIF-123] Some message"
          echo "  [PLM-P12-345] Some message"
          echo "  Coding style for \"[HIF-123] Some message\""
          echo "  Coding style for \"[PLM-P12-345] Some message\""
          exit 1
